name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy-azure-resources: 
    environment: production
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - name: az login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get SWA Url
      run: |
          echo "SWA_URL=$(az staticwebapp show -n relearn-angular-client-static-web-app --query 'defaultHostname')" >> $GITHUB_ENV   
          
  
    - name: Azure CLI script
      uses: azure/CLI@v1
      env:
        SWA_URL: ${{ env.SWA_URL }}
      with:
        inlineScript: |
          az rest  --method "patch" --uri "https://graph.microsoft.com/v1.0/applications/${{ secrets.AZURE_APP_OBJECT_ID }}"  --headers "{'Content-Type': 'application/json'}"  --body "{'spa': {'redirectUris': [ 'https://${{ env.SWA_URL }}', 'http://localhost:4200/' ]}}"
  

      # Deploy Bicep file
    - name: deploy resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./IaC/main.bicep
        failOnStdErr: false
        scope: 'subscription'
        region: eastus

    - name: Get SWA Token
      run: |
          echo "SWA_TOKEN=$(az staticwebapp secrets list -n relearn-angular-client-static-web-app --query 'properties.apiKey')" >> $GITHUB_ENV   

  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: deploy-azure-resources
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist/relearn-angular/browser" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
